[world]
name = "Cartridge World"
description = "Cartridge World"
website = "https://github.com/dojoengine/dojo-starter"
seed = "arcade"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "ARCADE"

[init_call_args]
"ARCADE-StarterpackRegistry" = [
    "0x5",
    "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec",
    "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec",
]

[writers]
"ARCADE" = [
    "ARCADE-StarterpackRegistry"
]
[owners]
"ARCADE" = ["ARCADE-StarterpackRegistry"]


[env]
rpc_url = "http://localhost:5050"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"
