packages:
  - client
  - packages/**
catalog:
  "@cartridge/ui": github:cartridge-gg/ui#460751b
  "@cartridge/arcade": 0.0.2
  "@cartridge/controller": 0.9.2
  "@cartridge/connector": 0.9.2
  "@starknet-react/core": 3.7.4
  "@starknet-react/chains": 3.1.3
  "@dojoengine/core": 1.7.0-preview.3
  "@dojoengine/sdk": 1.7.0-preview.3
  "@dojoengine/torii-client": 1.7.0-preview.3
  "@dojoengine/torii-wasm": 1.7.0-preview.3
  class-variance-authority: ^0.7.1
  starknet: 8.5.2
  tsup: 8.4.0
  typescript: "5.8"
