[package]
name = "collection"
version.workspace = true
edition.workspace = true

[dependencies]
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_access.workspace = true
openzeppelin_upgrades.workspace = true
graffiti.workspace = true
starknet.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[[target.starknet-contract]]
sierra = true
casm = false

[lib]
