[package]
name = "collection"
version.workspace = true
edition.workspace = true

[dependencies]
openzeppelin.workspace = true
graffiti.workspace = true
starknet.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[[target.starknet-contract]]
sierra = true
casm = false

[lib]
