[package]
name = "achievement"
version.workspace = true
edition.workspace = true

[dependencies]
dojo.workspace = true
dojo_macros.workspace = true
starknet.workspace = true

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.1" }
cairo_test = "2.11.4"

# dojo_cairo_test.workspace = true
# cairo_test.workspace = true

[lib]

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
