[world]
name = "Cartridge World"
description = "Cartridge World Achievements"
website = "https://github.com/dojoengine/dojo-starter"
seed = "bushido"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "game_center"
mappings = { "achievement" = [
    "m_Game",
    "m_Achievement",
], "game_center" = [
    "m_Game",
    "m_Achievement",
] }

[writers]
"game_center" = ["game_center-Actions"]

[env]
rpc_url = "https://api.cartridge.gg/x/bushido/katana"
account_address = "0x79e1341bc8e27b2ae2544fe902f0c9e723cfba8e37c47371d90385cc17265cc"
private_key = "0x506a3b48830c89357283236d8724f68d014d681499b2256e7589c950a4198c5"
