[world]
name = "Cartridge World"
description = "Cartridge World"
website = "https://github.com/dojoengine/dojo-starter"
seed = "arcade"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "ARCADE"

[init_call_args]
"ARCADE-Registry" = [
    "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753",
]

[writers]
"ARCADE" = ["ARCADE-Registry", "ARCADE-Slot", "ARCADE-Social", "ARCADE-Wallet"]

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"
