[package]
cairo-version = "2.8.4"
name = "quest_world"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
achievement = { path = ".." }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.0" }

[[target.dojo]]
build-external-contracts = [
    "achievement::models::index::Game",
    "achievement::models::index::Achievement",
    "achievement::events::index::AchievementCreation",
    "achievement::events::index::AchievementCompletion",
]

[profile.slot]
