[package]
cairo-version = "2.8.4"
name = "arcade"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }
controller = { path = ".." }
provider = { path = ".." }
registry = { path = ".." }
starknet = "2.8.4"
cairo_test = "2.8.4"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "controller::models::index::m_Account",
    "controller::models::index::m_Controller",
    "controller::models::index::m_Member",
    "controller::models::index::m_Signer",
    "controller::models::index::m_Team",
    "provider::models::index::m_Deployment",
    "provider::models::index::m_Factory",
    "registry::models::index::m_Access",
    "registry::models::index::m_Achievement",
    "registry::models::index::m_Game",
]

[profile.slot]
