[package]
name = "registry"
version.workspace = true
edition.workspace = true

[dependencies]
dojo.workspace = true
starknet.workspace = true
graffiti.workspace = true
collection = { path = "../collection" }

[dev-dependencies]
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_access.workspace = true
openzeppelin_upgrades.workspace = true
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[lib]
