name: Publish to npm

on:
  push:
    tags:
      - "v*"

env:
  WORKING_DIRECTORY: ./kits/typescript

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install

      - name: Build SDK
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build

      - name: Publish to npm
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
